import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, useUser, SignOutButton, SignedIn, SignedOut } from "@clerk/nextjs";
import { api } from "~/utils/api";
import { UserResource } from "@clerk/types";


const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { user } = useUser();


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className= "h-screen bg-slate-800">
        <div className="text-slate-200">
          <SignedIn>
            {user && `Hello ${user.firstName}`}
            <br />
            <SignOutButton />
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </div>
      </main>
    </>
  );
};

export default Home;
