import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import UserDetailsForm from "src/components/UserDetailsForm";
import StroopTest from "src/components/StroopTest";

import {
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";

const Home: NextPage = () => {
  const [backgroundColor, setBackgroundColor] = useState("bg-slate-800");

  const [userEmail, setUserEmail] = useState("");
  const [isRegistered, setIsRegistered] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {`@import url('https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&display=swap');`}
        </style>
      </Head>
      <main className={`h-screen ${backgroundColor}`}>
        <div className="flex flex-col text-slate-200">
          <SignedIn>
            <div className="m-4 flex items-center justify-end">
              <SignOutButton />
            </div>
            <br />
            <UserDetailsForm
              setUserEmail={setUserEmail}
              setIsRegistered={setIsRegistered}
            />
            {isRegistered && (
              <StroopTest
                userEmail={userEmail}
                setBackgroundColor={setBackgroundColor}
              />
            )}
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </div>
      </main>
    </>
  );
};

export default Home;
