import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import UserDetailsForm from "~/components/UserDetailsForm";
import StroopTest from "~/components/StroopTest";
import AnimatedInstructions from "~/components/AnimatedInstructions";

import { initialInstructions } from "../data/instructions";

import {
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-slate-800">
        <div className="text-slate-200">
          <SignedIn>
            <br />

            <UserDetailsForm />
            <AnimatedInstructions instructions={initialInstructions} />

            <StroopTest />
            <SignOutButton />
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
        </div>
      </main>
    </>
  );
};

export default Home;
